[package]
name = "edgetx-badapple-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
eyre = "0.6.8"
ndarray = "0.15.6"
opencv = "0.79.0"
tokio = { version = "1.27.0", features = ["full"] }
